site_name: ScrumSaga Documentation

pages:
    - 'Home': 'index.md'
    - 'Quick Start': 'quick_start.md'
    - 'Introduction': 'intro.md'
    - 'Use Cases': 'use_cases.md'
    - 'Overview': 'overview.md'
    - 'User Guide': 'user_guide.md'
    - 'Technical Reference': 'tech_ref.md'
    - 'About': 'about.md'

theme: readthedocs